version: 2.1
orbs:
  # Choose either one of the orbs below
  # welcome: circleci/welcome-orb@0.4.1
  aws-cli: circleci/aws-cli@2.0.3

jobs:
  # test-job:  
  #     docker:
  #       - image: cimg/base:stable
  #     steps:
  #       - checkout 
  #       - run: echo "hello world" 

  # create_infrastructure: 
  #     docker:
  #       - image: amazon/aws-cli
  #     steps:
  #       - checkout
  #       - run:
  #           name: Create Cloudformation Stack
  #           command: |
  #             aws cloudformation deploy \
  #               --template-file infra.yml \
  #               --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5} \
  #               --region us-east-2

  configure_infrastructure: 
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
              fingerprints: ["6d:80:ce:06:a3:d9:58:7c:76:f3:fb:30:5b:4b:7d:fd"] 
      - run:
          name: Install Ansible
          command: |
            apk add --update ansible
      - run:
          name: Run Playbook and Configure server
          command: |
            ansible-playbook -i inventory.txt main-remote.yml 
workflows:
  # Name the workflow
  myWorkflow:
    jobs:
      # - test-job
      # - create_infrastructure
      - configure_infrastructure